# Generated by Django 3.2.24 on 2024-03-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist_title', models.CharField(max_length=200)),
                ('place_of_origin', models.CharField(max_length=200)),
                ('date_display', models.CharField(max_length=200)),
                ('medium_display', models.CharField(max_length=200)),
                ('image_id', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('iiif_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('license_text', models.TextField(blank=True, null=True)),
                ('license_links', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
